KDAB/kuesa

src/core/gltf2importer/gltf2parser.cpp
The issue is that when the glTF parser creates QNode subclass
instances using operator new, we always only get the plain old
C++ objects. This is an issue when using QML to drive the
application and when you want to access properties on types that
have been registered with QML as extended types.
The QAbstractNodeFactory will automatically have inner factories
registered at application start up by the QML plugins. That means
we should use the factory to create the nodes rather than operator
new.
This commit does it only for Qt3DCore::QEntity to prove that it
works.
Without this commit accessing a Kuesa.Asset.node in QML code only
gives access to the basic QNode properties. With this commit we
get access to the properties defined on the QEntity extension
object too - namely the list of …
=> Use the node factory rather than operator new

src/core/shaders/graphs/kuesa_metalroughfunction_prototype.frag.json, src/core/shaders/graphs/metallicroughness.frag.json, src/core/shaders/graphs/metallicroughness.qt3d
The .qt3d file was using an old prototype and when exporting to a .frag.json, it failed. This patch updates the .qt3d file and the .frag.json created with the new .qt3d file.
=> Update gltf2material graph pbr node

src/core/core.pro, src/core/gltf2exporter/dracocompressor_p.cpp, src/core/gltf2exporter/dracocompressor_p.h, src/core/gltf2exporter/gltf2exporter.pri, src/core/gltf2exporter/gltf2exporter_p.cpp, src/core/gltf2exporter/gltf2exporter_p.h, src/core/gltf2importer/gltf2context.cpp, src/core/gltf2importer/gltf2context_p.h, src/core/gltf2importer/gltf2importer.h, src/core/gltf2importer/gltf2importer.pri, src/core/gltf2importer/gltf2keys_p.h, src/core/gltf2importer/gltf2parser.cpp, src/core/gltf2importer/meshparser.cpp, src/core/metallicroughnessmaterial.cpp, tests/auto/assets/car, tests/auto/gltfexporter/gltfexporter.pro, tests/auto/gltfexporter/tst_gltfexporter.cpp, tools/assetpipelineeditor/assetpipelineeditor.pro, tools/assetpipelineeditor/exportdialog.cpp, tools/assetpipelineeditor/exportdialog.h, tools/assetpipelineeditor/exportdialog.ui, tools/assetpipelineeditor/mainwindow.cpp, tools/assetpipelineeditor/mainwindow.h, tools/assetpipelineeditor/mainwindow.ui, tools/assetpipelineeditor/meshinspector.cpp
This pull request starts to have something that looks like a working implementation (see https://github.com/KDAB/kuesa/pull/16/files?w=1 to get a diff without the whitespace changes - github really ought to have a nice button for this).
* Compressing and reloading these in Kuesa: 
- https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Box/glTF
- https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Cube/glTF
- https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedCube/glTF
- https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxAnimated/glTF
- https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck/glTF
- https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Buggy/glTF
- The DodgeViper example
* …
=> Compress draco 2

src/core/gltf2exporter/gltf2exporter_p.cpp, src/core/gltf2exporter/gltf2exporter_p.h, tests/auto/gltfexporter/tst_gltfexporter.cpp, tools/assetpipelineeditor/exportdialog.cpp
Before it was not possible to know in which file the compressed buffer was written.
This will be useful to perform statistics for instance (e.g. for #38 or later if we also do it in the UI).
=> Export: change API in order to get the output filename

src/core/gltf2exporter/gltf2exporter_p.cpp, src/core/gltf2exporter/gltf2exporter_p.h, src/core/gltf2importer/bufferparser.cpp, src/core/gltf2importer/gltf2context.cpp, src/core/gltf2importer/gltf2context_p.h, src/core/gltf2importer/imageparser.cpp, tools/assetpipelineeditor/exportdialog.cpp
This saves a list of the files referenced by a .gltf in the gltf context so that we can check them quickly before exporting.
=> Warn the user about the assets that may be overwritten while exporting.

README.md, src/3rdparty/mikktspace/mikktspace.c, src/3rdparty/mikktspace/mikktspace.h, src/3rdparty/mikktspace/mikktspace.pri, src/core/core.pro, src/core/gltf2importer/gltf2importer.pri, src/core/gltf2importer/meshparser.cpp, src/core/gltf2importer/meshparser_utils.cpp, src/core/gltf2importer/meshparser_utils_p.h, tests/auto/meshparser/tst_meshparser.cpp
glTF 2.0 requires we compute tangents if necessary using MikkTSpace. 
We could only generate them if the material for a primitive has a normal map, but since we can change on runtime the material, I have chosen to compute them always, is possible. 
Probably still need some massage for making it faster.
=> Compute tangents if not provided

tools/assetpipelineeditor/mainwindow.cpp, tools/assetpipelineeditor/mainwindow.h
took pauls approach moved to asset pipeline editor directly
and added headroom to the numbers.
worked for the scene i've tested so far...
=> default cam for asset viewer

src/core/gltf2importer/meshparser.cpp, src/core/gltf2importer/meshparser_utils.cpp, tests/auto/meshparser/tst_meshparser.cpp
- TEXCOORD_1 and TEXCOORD_2 to Qt3DRender::QAttribute name was missing
- Context was missing accessor info for checkForAssetPipelineEditorProperties
- Rewrote geometryIsGLTF2Valid to make it easier to understand
=> Fix unit tests:

src/core/gltf2importer/gltf2context_p.h, src/core/gltf2importer/gltf2parser_p.h, tools/assetprocessor/assetprocessor.pro, tools/assetprocessor/main.cpp
The command-line API is fairly simple for now (it only allows to set the overall quantization level) - I think that as @seanharmer mentioned the correct thing to do would be to have a project file to indicate the whole set of compression parameters.
=> Add a command-line tool for asset compression

src/core/shaders/es2/kuesa_metalrough.inc.frag, src/core/shaders/es3/kuesa_metalrough.inc.frag
got QOpenGLShader::compile(Fragment): ERROR: 0:81: '=' :
assigning non-constant to 'const highp float'
Ticket-Id: KUE-631
=> Fix Shader Issue Under ES2 / Windows

src/core/gltf2exporter/dracocompressor_p.cpp
CHAR_MIN doesn't seem to be the same as std::numerit_limits<qint8>::min()
on arm64 Android.
=> Fix compilation on Android

examples/kuesa/car-scene/qml/MainScene.qml, tools/assetpipelineeditor/main.qml
The DirectionalLight would assume a global direction, while the Camera
could only provide a direction relative to its parent entities
coordinate system, thus screwing up.
=> Replace DirectionalLight with PointLight that moves with the camera

src/core/gltf2importer/meshparser_utils.cpp
A .gltf file exported from Blender contained JOINTS_1 and WEIGHTS_1, so we either need this patch, or add these named attributes.
=> Ignore unknown glTF vertex attributes

src/core/gltf2importer/animationparser.cpp
To make sure we have the right number of components for a given channel type
=> AnimationParser: add additional check

src/core/gltf2exporter/dracocompressor_p.cpp
Currently when exporting generated tangents, no glTF name was set
which would then generate an invalid json while exporting.
This makes this mechanism more robust for future cases.
=> Ensure that the attributes have a name for draco compression

examples/kuesa/car-scene/car-scene.pro, examples/kuesa/car-scene/main.cpp
This looks like it is necessary for arm boards where the linker fails
due to the large dds files.
=> Put resources in external files in the common case.

src/core/metallicroughnesseffect.cpp, src/core/metallicroughnesseffect.h, tools/assetpipelineeditor/meshinspector.cpp
Special highlight material still needs.brdfLUT texture. We steel it
from the material of the selected entity. Needs to be done every time
in case another model was loaded and the previous texture was deleted.
Q: what happens when the texture is deleted, does the QParameter know about it?
Does the effect need to track the life time of the texture then? Or should it be 
promoted as a proper parameter like the other maps?
=> Fix selection material

src/core/shaders/es2/light.inc.frag
OES_texture_float and OES_texture_float_linear have been enabled for ES2. Maybe we would prefer to `require` them instead?
Task-Id: KUE-643
=> add required extensions for ES2 HDR IBL

README.md, src/quick/imports/kuesaplugin.cpp, tools/assetpipelineeditor/orbitcameracontroller.cpp, tools/gltfViewer/Info.plist.in, tools/gltfViewer/README.md, tools/gltfViewer/gltfViewer.pro, tools/gltfViewer/main.cpp, tools/gltfViewer/main.qml, tools/gltfViewer/qml.qrc, tools/tools.pro
Opens and renders gltf files using just a QWindow, no QML, no widgets.
On macOS this gets associated to .gltf files.
Supports drag & dropping files on the opened window.
Will be useful to debug performance without interference from other rendering.
=> Simple gltfViewer

src/core/gltf2importer/gltf2importer.cpp, src/core/gltf2importer/gltf2parser.cpp, src/core/gltf2importer/gltf2parser_p.h, tests/auto/gltfexporter/tst_gltfexporter.cpp, tests/auto/gltfparser/tst_gltfparser.cpp
This puts the main glTF parsing in a QThread.
Some wrangling is needed because adding elements to the SceneEntity has to be done in the GUI thread, so the main `parse` method is split between `parse` which only does parsing and works in another thread, and `setupScene` which needs to be called from the gui thread.
There are certainly still some thread-safety bugs - it would be safer I think to restart from a new
clean SceneEntity when loading.
Maybe the approach is woefully incorrect - please bash :)
=> Threaded parsing

src/core/shaders/es2/light.inc.frag
This reverts commit 62195e84437983462eeb2e4cf4ac6cbccad8f84a which breaks on the platform it's supposed to fix.
The extension settings must come BEFORE any glsl code, not sure how you achieve that with the shader builder.
=> Revert "add required extensions for ES2 HDR IBL"
