- examples/kuesa/car-scene/qml/CarCameraController.qml
Paul's original change moved to github
Task-Id: TRDSHW-818
> car-scene: properly handle camera min and max tilt

- README.md
- config_help.txt
- src/core/configure.json
- src/core/configure.pri
- src/core/core.pro
Support setting DRACOSDK env var to point to where Draco include and
lib folders are
> Add ability to configure where draco is installed

- tools/qtc_templates/kuesa/project/empty/wizard.json
> Fix wizard for 5.12

- examples/kuesa/assets/envmaps/kdab-studiosky-small/kdab-studiosky-small_16f_irradiance_es2.dds
- examples/kuesa/assets/envmaps/kdab-studiosky-small/kdab-studiosky-small_16f_specular_es2.dds
- examples/kuesa/assets/envmaps/neuer_zollhof/envmap-neuer-zollhof-16f.qrc
- examples/kuesa/assets/envmaps/neuer_zollhof/neuer_zollhof_16f_irradiance_es2.dds
- examples/kuesa/assets/envmaps/neuer_zollhof/neuer_zollhof_16f_specular_es2.dds
- examples/kuesa/assets/envmaps/pink_sunrise/envmap-pink-sunrise-16f.qrc
- examples/kuesa/assets/envmaps/pink_sunrise/pink_sunrise_16f_irradiance_es2.dds
- examples/kuesa/assets/envmaps/pink_sunrise/pink_sunrise_16f_specular_es2.dds
- src/core/shaders/es2/kuesa_metalrough.inc.frag
- src/core/shaders/es2/light.inc.frag
- src/core/shaders/es2/skybox.frag
- src/core/shaders/gl3/skybox.frag
- tools/cubemaptooctahedralmap/3rdparty/gli-0.8.2.0/gli/core/save_dds.inl
- tools/cubemaptooctahedralmap/CopyOutputToSSBO.qml
- tools/cubemaptooctahedralmap/main.qml
- tools/cubemaptooctahedralmap/ssbobuffer.cpp
- tools/cubemaptooctahedralmap/ssbobuffer.h
- tools/ddspreviewer/TexturePreview.qml
- tools/ddspreviewer/ddsheaderparser.cpp
- tools/ddspreviewer/ddsheaderparser.h
- tools/ddspreviewer/ddspreviewer.pro
- tools/ddspreviewer/main.cpp
- tools/ddspreviewer/main.qml
- tools/ddspreviewer/qml.qrc
- tools/tools.pro
> Add Tool to inspect DDS header and preview texture

- src/core/shaders/graphs/metallicroughness.frag.json
Matching similar changes made in qt3d
> Fix PBR shaders

- src/core/framegraphes/forwardrenderer.cpp
If main clear colour changes, the clear node for effects needs to use
the same.
> Fix colour in effect clearing

- src/core/shaders/gl3/kuesa_metalrough.inc.frag
Improves the specular highlights for point, directional and spotlights. The environmental specular reflections already use GGX due to the way we generate the convolved envmap textures. We could go further in the future by sampling multiple times from the original environment map in random directions. Of course this increases the cost of the fragment shader so mostly relevant on desktop. This pre-convolved solution is likely fine for embedded use and our needs there.
Blinn Phong (before)
GGX (after). Notice the much nicer highlights from the directional light in the scene.
> Switch from Blinn-Phong to GGX specular model in PBR Metal Rough

- src/core/metallicroughnesseffect.cpp
- tests/manual/forwardrenderer_scene/main.qml
- tests/manual/mapped_animations/main.qml
Hack in no longer needed with change in qt5.12. Actually wonder if it should be conditionally compiled in if qt ver is < 5.12.2?
Also includes some clang-tidy formatting changes.
> Cleanup effects

- examples/kuesa/car-scene/qml/CarCameraController.qml
It's way too sensitive with a mouse when rotating.
> Reduce the camera controller sensitivity somewhat

- src/core/gltf2importer/gltf2parser.cpp
Did it for some creations, but not all.
A lot of them don't end up in user facing containers (like collections) so not sure they need to be
> Create objects using factory

- examples/kuesa/car-scene/qml/IdleDemoAnimation.qml
- examples/kuesa/car-scene/qml/MainMenu.qml
- examples/kuesa/car-scene/qml/MainScene.qml
- examples/kuesa/car-scene/qml/main.qml
- examples/kuesa/car-scene/qml/qml.qrc
- src/core/gltf2importer/gltf2parser_p.h
- tools/assetpipelineeditor/animationwidget.cpp
adds animations to show of skybox/env map, opacity mask, changing colours.
Also add a text overlay indicating what is going on
> More demo animations

- src/core/animationplayer.cpp
- src/core/framegraphes/forwardrenderer.cpp
- src/core/framegraphes/transparentrenderstage.cpp
- src/core/fx/gaussianblureffect.cpp
- src/core/gltf2importer/gltf2parser.cpp
- src/core/gltf2importer/gltf2parser_p.h
- src/core/gltf2importer/textureparser.cpp
- src/quick/imports/postfxlistextension.h
- tools/assetpipelineeditor/animationwidget.cpp
- tools/assetpipelineeditor/assetinspector.h
- tools/assetpipelineeditor/assetinspectorwidget.cpp
- tools/assetpipelineeditor/meshinspector.cpp
- tools/assetpipelineeditor/meshinspector.h
- tools/assetpipelineeditor/orbitcameracontroller.cpp
- tools/cubemaptooctahedralmap/CopyOutputToSSBO.qml
- tools/cubemaptooctahedralmap/FlatOctahedronEntity.qml
- tools/cubemaptooctahedralmap/OctahedralMapPreview.qml
- tools/cubemaptooctahedralmap/OctahedralSkybox.qml
- tools/cubemaptooctahedralmap/main.cpp
- tools/cubemaptooctahedralmap/main.qml
- tools/cubemaptooctahedralmap/ssbobuffer.cpp
- tools/cubemaptooctahedralmap/ssbobuffer.h
- tools/ddspreviewer/TexturePreview.qml
- tools/ddspreviewer/ddsheaderparser.cpp
- tools/ddspreviewer/ddsheaderparser.h
from compiler, clazy, krazy, clang-tidy
> Fix Warnings

- src/core/core.pri
- src/core/kuesa_global_p.h
> Add KUESA_PRIVATE_EXPORT macro

- tools/assetpipelineeditor/collectionmodel.cpp
Useful when looking at performance.
> Print number of entries in collection

- src/core/gltf2exporter/gltf2exporter_p.cpp
Breaks CI.
Also clang-format changes.
> Fix broken build with no Draco

- src/core/gltf2exporter/gltf2exporter_p.cpp
Also, I'm wondering if the export UI shouldn't allow the user to choose if he wants to embed existing data maybe ?
> Exporter: support exporting files with embedded base64 buffers

- src/core/gltf2exporter/gltf2exporter_p.cpp
> Fix a potential infinite loop when exporting

- src/core/gltf2exporter/dracocompressor_p.cpp
- src/core/gltf2importer/animationparser.cpp
- src/core/gltf2importer/animationparser_p.h
- src/core/gltf2importer/bufferaccessorparser.cpp
- src/core/gltf2importer/bufferaccessorparser_p.h
- src/core/gltf2importer/bufferparser.cpp
- src/core/gltf2importer/bufferviewsparser.cpp
- src/core/gltf2importer/bufferviewsparser_p.h
- src/core/gltf2importer/cameraparser.cpp
- src/core/gltf2importer/gltf2context.cpp
- src/core/gltf2importer/gltf2context_p.h
- src/core/gltf2importer/imageparser.cpp
- src/core/gltf2importer/layerparser.cpp
- src/core/gltf2importer/materialparser.cpp
- src/core/gltf2importer/materialparser_p.h
- src/core/gltf2importer/meshparser.cpp
- src/core/gltf2importer/meshparser_p.h
- src/core/gltf2importer/nodeparser.cpp
- src/core/gltf2importer/nodeparser_p.h
- src/core/gltf2importer/sceneparser.cpp
- src/core/gltf2importer/sceneparser_p.h
- src/core/gltf2importer/skinparser.cpp
- src/core/gltf2importer/skinparser_p.h
As for instance char might be an unsigned char on Arm.
Task-Id: KUE-580
> Use Qt type typedefs

- src/core/gltf2importer/animationparser.cpp
- src/core/gltf2importer/bufferaccessorparser.cpp
- src/core/gltf2importer/bufferaccessorparser_p.h
- src/core/gltf2importer/meshparser.cpp
- src/core/gltf2importer/meshparser_p.h
- src/core/gltf2importer/skinparser.cpp
- src/core/gltf2importer/textureparser.cpp
- src/core/sceneentity.cpp
- src/core/sceneentity.h
- tests/auto/assets/SimpleSparseAccessor.gltf
- tests/auto/assets/SimpleSparseAccessorNoBufferView.gltf
- tests/auto/assets/draco/Box_optional.gltf
- tests/auto/bufferaccessorparser/tst_bufferaccessorparser.cpp
- tests/auto/gltfparser/tst_gltfparser.cpp
data copying logic is flawed right now...
> Sparse accessor

- src/core/gltf2importer/meshparser.cpp
- tools/assetpipelineeditor/Info.plist.in
- tools/assetpipelineeditor/create_macos_installer.sh.in
Mac code signing and buffer index handling when using draco
> Various fixes

- src/core/shaders/es2/simple.vert
- src/core/shaders/es2/skinned.vert
- src/core/shaders/es3/simple.vert
- src/core/shaders/es3/skinned.vert
- src/core/shaders/gl3/passthrough.vert
- src/core/shaders/gl3/simple.vert
- src/core/shaders/gl3/skinned.vert
- src/core/shaders/gl3/skybox.frag
- src/core/shaders/gl3/skybox.vert
To please some GLSL compiler which error out otherwise
> Move version directive on top of license header

- tools/assetpipelineeditor/camerawidget.cpp
- tools/assetpipelineeditor/camerawidget.h
- tools/assetpipelineeditor/camerawidget.ui
Allows to easily get reproducable cameras between runs to be able
to compare images.
> Implement saving and loading camera settings

- examples/kuesa/car-scene/qml/MainScene.qml
- tools/assetpipelineeditor/main.qml
This will fix the ViewAll, but keep the lighting intact
> Parent PointLight to the camera, not to its parent

- examples/kuesa/car-scene/car-scene.pro
- examples/kuesa/car-scene/main.cpp
Useful for starting app on remote device from Creator
> Fix deployment of resource files

- src/core/gltf2exporter/gltf2exporter_p.cpp
- tools/tools.pro
fix build with no draco and enable some tools for embedded
> Fixes for working on iMX6

- src/core/metallicroughnesseffect.cpp
- src/core/metallicroughnesseffect.h
Factor out some of the repeated code in MetallicRoughnessEffect.
> Introduce MetallicRoughnessTechnique

- src/core/gltf2importer/meshparser.cpp
createAttribute doesn't use any draco stuff and is used in the non draco code path. Therefore, it fails to link in Android, where draco is disabled.
> Unhide createAttribute from DRACO ifdef
